modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://www.github.com/Stardust-Labs-MC/Terralith/issues"
license = "Stardust Labs License"

[[mods]]
modId = "terralith"
version = "${version}"
displayName = "Terralith"
authors = "Stardust Labs & CristelKnight"
description = "Terralith ~ Overworld Evolved (v2.2.4 for 1.18.2)"
logoFile = "pack.png"

[[dependencies.terralith]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.terralith]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"